### ISSUE TITLE
Module not found chart.js

### ISSUE THREAD

**Issue by josephpogue** [jtcheng26/ig-dm-analyzer#1]
In the Charts component, you cannot import chart.js because this file is missing

**Comment by jtcheng26** [comment]
Just added it to package.json. Should be fixed now.

**Comment by josephpogue** [comment]
I was wondering if you tried downloading it because doesn't seem to be working for me.
I downloaded the file, "npm install", and "npm start", but still doesn't work

**Comment by jtcheng26** [comment]
The issue was that I accidentally installed some of the packages in an outside folder containing my local repo. I added the dependencies and cloned the repo in a different directory and it's working for me now, so let me know if you're still having issues. Thanks for bringing this to my attention.
